spring:
  application:
    name: project
  datasource:
    url: jdbc:postgresql://localhost:8880/Lib
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql  
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
springdoc:
  swagger-ui:
    path : /swagger-ui-library.html